### ISSUE TITLE
Using both populate and seq_populate doesn't create the expected data set

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/cassandra-test-and-deploy#115]
Trying to create a data set of ~240GB.
The command line for the stress command used: 
./ec2-stress.sh 1 -e "load_name=scylla.3ndsmll_w_240gb" -e "server=Scylla" -e "command=write" -e "populate=75000000" -e "stress_options='-schema \"replication(factor=3)\" -errors ignore'" -e "command_options='cl=QUORUM -mode native cql3'" -e "seq_populate=75000000" -e "clean_data=true"

Did not create a 750000000 records,
Is seq_populate and populate mutex?

Pushing into the command options the following line (n=75000000) helped create the needed workload:
./ec2-stress.sh 1 -e "load_name=scylla.3ndsmll_w_240gb" -e "server=Scylla" -e "command=write" -e "stress_options='-schema \"replication(factor=3)\" -errors ignore'" -e "command_options='n=75000000 cl=QUORUM -mode native cql3'" -e "seq_populate=75000000" -e "clean_data=true"

**Comment by tzach** [comment]
> Is seq_populate and populate mutex?

Should not be. `seq_populate` is translated to `-pop seq={{range}}` where range is different per loader
Source: https://github.com/scylladb/cassandra-test-and-deploy/blob/master/stress.yaml#L68

`-pop` affect the distribution, not the number of operations.

source: https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsCStress_t.html

**Comment by tzach** [comment]
@eyalgutkind I'm closing this since the script does what is expected as explained above.
Reopen is you do not agree.
