### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by rokka-n** [scylladb/cassandra-test-and-deploy#126]
Hi!

I was able to create a db cluster and loadgenerators, but then no scripts can work with I guess inventory:

```
./ec2-terminate.sh
ERROR! Specified --limit does not match any hosts
```

How does ansible knows where stuff is?

**Comment by dorlaor** [comment]
It gets it from your AWS credentials.

**Comment by rokka-n** [comment]
Ok, it makes sense - since scripts do create hosts.

But still load tests and ec2_terminate fail. Where would you usually look to figure it out? Sorry, my ansible skills are bit rusty.

**Comment by dorlaor** [comment]
I'm puzzled that the creation did work and terminate didn't.
Please run the script with max verbosity (both ansible and the shell) and
we'll see what's the problem.

**Comment by rokka-n** [comment]
I forgot to mention, I've disabled public IPs assignment. Maybe roles relying on it or something?

This is how create looks like, there are lots of skipped tasks.
`./ec2-setup-scylla.sh -e "instance_type=i2.xlarge" -e "cluster_nodes=3"`

```
TASK [Give everyone a minute or two] *******************************************
task path: cassandra-test-and-deploy/roles/scylla-config/tasks/start.yaml:19
skipping: [x.x.1.57] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}

PLAY RECAP *********************************************************************
x.x.1.181                 : ok=4    changed=0    unreachable=0    failed=0
x.x.1.205                 : ok=4    changed=0    unreachable=0    failed=0
x.x.1.57                  : ok=4    changed=0    unreachable=0    failed=0
localhost                  : ok=14   changed=6    unreachable=0    failed=0
```

Err, this doesn't look right.

**Comment by dorlaor** [comment]
@tzach, our Ansible and cassandra-test-and-deploy expert should have a look

**Comment by tzach** [comment]
Lots of skipped tasks is fine, every time there is an Ansible condition, non-selected tasks are skipped.
My guess is you have a problem with your EC2 inventory, which is used only in terminating and running stress (not in the setup phase.)

Once you have a running cluster, please run `./inventories/ec2/ec2.py` and paste the results - which should include all your running servers.
Also please check you set the env-var ANSIBLE_EC2_PREFIX, it is used to tag your EC2 instances.

**Comment by rokka-n** [comment]
./inventories/ec2/ec2.py just prints all instances in the account. 
Prefix was also exported.

**Comment by rokka-n** [comment]
It looks like its loading inventory first time this runs, because there is a 10 or so seconds delay. 

```
echo "tag_user_`echo $ANSIBLE_EC2_PREFIX`"
tag_user_xxx-scylla-test

ansible-playbook -vvvv -i inventories/ec2/ terminate.yaml --limit "tag_user_`echo $ANSIBLE_EC2_PREFIX`"
Using /Users/xxx/cassandra-test-and-deploy/ansible.cfg as config file
ERROR! Specified --limit does not match any hosts
```

Is that inventory dynamically fetched or it's stored somewhere? I guess I don't quite understand how it's organized...

**Comment by tzach** [comment]
> ./inventories/ec2/ec2.py just prints all instances in the account.

This is the expected result.
Can you attach the full result here?

> echo "tag_user_`echo $ANSIBLE_EC2_PREFIX`"
> tag_user_xxx-scylla-test

is xxx your user name? if so, this is fine.

**Comment by rokka-n** [comment]
There is a lot of internal information in the output, I'll reply over email.

**Comment by rokka-n** [comment]
I've looked at the output carefully and noticed that it returns only hosts with public IPs. Is it intentional? How to make it return private ones only?

**Comment by tzach** [comment]
> I've looked at the output carefully and noticed that it returns only hosts with public IPs. Is it intentional? How to make it return private ones only?

Its probably it, and may be related to a parameter in `inventories/ec2/ec2.ini`
I'm looking into it

**Comment by tzach** [comment]
the following updates to `inventories/ec2/ec2.ini` 
```
-destination_variable = public_dns_name
+destination_variable = private_dns_name
-vpc_destination_variable = ip_address
+vpc_destination_variable = private_ip_address
```
expose internal IP instead of external, and list servers with out external IP as well.
I tested ./ec2-terminate.sh with the above change, and it works for servers with and without external IP, but I have not yet run a full test including stress with the new config.

**Comment by rokka-n** [comment]
Thanks! I found it as well (except that `destination_variable = private_ip_address`) since there is no name resolution from laptops.

Running now into ansible problems now. 
It lists them correctly but fails to delete, maybe I should try full cycle, create-test-destroy

```
ansible-playbook -vv --check -i inventories/ec2/ terminate.yaml --limit "tag_user_`echo $ANSIBLE_EC2_PREFIX`"
Using cassandra-test-and-deploy/ansible.cfg as config file
...

PLAY [loadgen_nodes] ***********************************************************

TASK [Terminate instance(s)] ***************************************************
task path: cassandra-test-and-deploy/terminate.yaml:31
skipping: [xx.xx.1.146] => {"changed": false, "msg": "remote module (ec2) does not support check mode", "skipped": true}
skipping: [xx.xx.1.130] => {"changed": false, "msg": "remote module (ec2) does not support check mode", "skipped": true}

PLAY RECAP *********************************************************************
...
xx.xx.1.63                  : ok=1    changed=0    unreachable=0    failed=0
xx.xx.1.66                  : ok=1    changed=0    unreachable=0    failed=0
```

and when actually applying change:

```
fatal: [xx.x.1.44]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "assign_public_ip": false,
            "aws_access_key": null,
...
            "zone": null
        },
        "module_name": "ec2"
    },
    "msg": "boto required for this module"
}
```

Hmmm. Any idea what else ansible wants?

```
pip list boto | grep boto
boto (2.46.1)
```

**Comment by tzach** [comment]
I have boto (2.45.0) 
What ansible version are you using?

**Comment by tzach** [comment]
Maybe its a mac related issue like the one presented here
https://github.com/ansible/ansible/issues/5734
or
http://stackoverflow.com/questions/37253793/boto-required-for-this-module-ec2-elb-lb

The second suggest setting PYTHONPATH
I will need to find a mac to validate.

**Comment by rokka-n** [comment]
Seems like this fixed the problem with "boto not found":
`sudo /usr/bin/python -m pip install boto`

Ansible was the latest version

```
ansible --version
ansible 2.2.2.0
```

Are you using this for any serious work? 

I also noticed that everything installed into the same zone, so such tests are not simulating anything close to real world scenarios. Were there any difference in performance for multi-zone setup?

**Comment by tzach** [comment]
Glad it's working now!

> Are you using this for any serious work?

We are using this script daily to test Scylla. We are not yet using it to deploy Scylla production clusters ourselves, altho similar Ansible playbooks are used for that by others.

> I also noticed that everything installed into the same zone, so such tests are not simulating anything close to real world scenarios. Were there any difference in performance for multi-zone setup?

There is an option to setup a multi region cluster, not a multi zone. I assume multi zone will introduce some latency between nodes.

**Comment by rokka-n** [comment]
Yeah, finally ansible doing useful stuff (these never working as expected
configuration management systems)

I wanted to confirm the results: 3 x i2.xlarge data + 5 x m3.large produced
15k/s "row rate" for each loadgen instance

Does it mean total for cluster was 60k/s?

replication(factor=2)
Populate=5000000
Command=mixed

But disk util was only few GB (from 800GB available for this instance
size).

What would happen if data consume 80% of disk and there is a failed node(s)?

**Comment by tzach** [comment]
> I wanted to confirm the results: 3 x i2.xlarge data + 5 x m3.large produced
> 15k/s "row rate" for each loadgen instance
> 
> Does it mean total for cluster was 60k/s?

Yes. Note that each writes update two servers (RF=2)

> What would happen if data consume 80% of disk and there is a failed node(s)?

Not sure what you mean.

* its always recommended to keep 50% of the disk free for compaction and some extra space
* a fail node does not mean other will take it place automatically. For that, you need to decommission the node.

@rokka-n since the original issue is solved, I'm closing this issue. I suggest to continue this discussion on the Scylla user list:
https://groups.google.com/forum/#!forum/scylladb-users

**Comment by rokka-n** [comment]
Thank you!
