### ISSUE TITLE
Clean stress yaml

### ISSUE THREAD

**Issue by tzach** [scylladb/cassandra-test-and-deploy#22]
https://github.com/scylladb/cassandra-test-and-deploy/pull/21 introduce required functionality, but made the already complex stress.yaml even more complex.
One way to simplify it is creating a bash wrapper script around cassandra-stress, uploading it as part of the loader role, and call this script from stress yaml.

**Comment by tzach** [comment]
@glommer feel free to comment

**Comment by glommer** [comment]
it makes sense to me.

We still need to decide whether or not to run such script from the yaml. Can we pass variables to the said script through the recipe? If we can, we can decide whether or not to  setup the bindings based on that

**Comment by tzach** [comment]
> We still need to decide whether or not to run such script from the yaml. Can we pass variables to the said script through the recipe? If we can, we can decide whether or not to setup the bindings based on that

Yes, we can pass parameter from YAML to the script, same way we do now for cassandra-stress.
We can go further and pass **the entire** cassandra-stress command as one big parameter, avoiding all the many `-e` parameter syntax.

The only variable the playbook (yaml) will inject is the DB nodes ips.
