### ISSUE TITLE
Need to add option to split load between loaders

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/cassandra-test-and-deploy#95]
Need to add the option to split write load between all loaders.
Currently when using the write command the each loader write the same keys

For example if we have to loaders
`./ec2-stress.sh 1 -e "server=Scylla" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_write" -e "threads=2500" -e "command_options='cl=QUORUM n=1000000 -mode native cql3 -pop seq=1..1000000'"`

Need to be split like
`./ec2-stress.sh 1 -e "server=Scylla" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_write" -e "threads=2500" -e "command_options='cl=QUORUM n=500000 -mode native cql3 -pop seq=1..500000'"`

`./ec2-stress.sh 1 -e "server=Scylla" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_write" -e "threads=2500" -e "command_options='cl=QUORUM n=500000 -mode native cql3 -pop seq=500001..1000000'"`

**Comment by tzach** [comment]
What is the motivation for this? having each client with a different range of keys seems less realistic

**Comment by dorlaor** [comment]
On Jul 3, 2016 8:25 PM, "Tzach Livyatan" notifications@github.com wrote:

> What is the motivation for this? having each client with a different
> range of keys seems less realistic

It's for parallel data upload as a preparation step

**Comment by nirmaayan** [comment]
@tzach test failed 

below is -vvvv output

<54.172.157.232> ESTABLISH CONNECTION FOR USER: fedora
<52.201.218.243> ESTABLISH CONNECTION FOR USER: fedora

```
fatal: [54.172.157.232] => One or more undefined variables: 'ec2_tag_index' is undefined
fatal: [52.201.218.243] => One or more undefined variables: 'ec2_tag_index' is undefined
FATAL: all hosts have already failed -- aborting
```
